spring.application.name=demo
server.servlet.context-path=/api
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/agroprecios}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true